//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oxford.Brc.Clinical.Data.Warehouse.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Oxford.Brc.Clinical.Data.Warehouse.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string custom_dictionary {
            get {
                return ResourceManager.GetString("custom_dictionary", resourceCulture);
            }
        }
        
        internal static string medical_acronyms {
            get {
                return ResourceManager.GetString("medical_acronyms", resourceCulture);
            }
        }
        
        internal static string medical_terms {
            get {
                return ResourceManager.GetString("medical_terms", resourceCulture);
            }
        }
        
        internal static string words_alpha {
            get {
                return ResourceManager.GetString("words_alpha", resourceCulture);
            }
        }
        
        internal static string custom_full_text_markers {
            get {
                return ResourceManager.GetString("custom_full_text_markers", resourceCulture);
            }
        }
    }
}
